spring.application.name=gateway

server.port=9090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${server.port}

spring.cloud.gateway.routes[0].id=demo
spring.cloud.gateway.routes[0].uri=lb://DEMO
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/demo/**


spring.cloud.gateway.actuator.verbose.enabled=true

management.endpoint.health.show-details=ALWAYS
management.endpoints.web.exposure.include=*