spring.application.name=gateway

server.port=9090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${server.port}



management.endpoint.health.show-details=ALWAYS
management.endpoints.web.exposure.include=*


# AUTH-SERVICE GATEWAY
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

# USER-SERVICE GATEWAY
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/**

# DRIVER-SERVICE GATEWAY
spring.cloud.gateway.routes[2].id=driver-service
spring.cloud.gateway.routes[2].uri=lb://DRIVER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/drivers/**

# RIDE-SERVICE GATEWAY
spring.cloud.gateway.routes[3].id=ride-service
spring.cloud.gateway.routes[3].uri=lb://RIDE-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/rides/**

# ORDER-SERVICE GATEWAY
spring.cloud.gateway.routes[4].id=oder-service
spring.cloud.gateway.routes[4].uri=lb://ODER-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/orders/**

spring.cloud.gateway.actuator.verbose.enabled =true


#spring.cloud.gateway.routes[0].id=demo
#spring.cloud.gateway.routes[0].uri=lb://DEMO
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/demo/**

#spring.cloud.gateway.actuator.verbose.enabled=true